environment: staging
namespace: nlp

apps:
  api:
    deployment:
      repository: paralect/common
      replicas: 1
      livenessProbe:
        path: /health
        port: 3001
        initialDelaySeconds: 6000
        periodSeconds: 12000
      imagePullPolicy: Always
      env:
        - name: APP_ENV
          value: "staging"
      ports:
        - containerPort: 3001
          protocol: TCP
    services:
      - name: api
        type: ClusterIP
        ports:
          - protocol: TCP
            port: 80
            targetPort: 3001
        ingress:
          host: nlp-demo-api.paralect.net
      # - name: socket
      #   type: ClusterIP
      #   ports:
      #     - protocol: TCP
      #       port: 80
      #       targetPort: 8082
      #   ingress:
      #     host: socket.paralect.net

  web:
    deployment:
      repository: paralect/common
      replicas: 1
      livenessProbe:
        path: /health
        port: 3002
        initialDelaySeconds: 3
        periodSeconds: 5
      imagePullPolicy: Always
      env:
        - name: APP_ENV
          value: "staging"
      ports:
        - containerPort: 3002
          protocol: TCP
    services:
      - name: web
        type: ClusterIP
        ports:
          - protocol: TCP
            port: 80
            targetPort: 3002
        ingress:
          host: nlp-demo.paralect.net

imageCredentials:
  enabled: true
  secretName: regcred
